"""add_rate_limit_store

Revision ID: f1a2b3c4d5e6
Revises: e9c9aef67bb5
Create Date: 2026-05-08 10:00:00.000000

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1a2b3c4d5e6'
down_revision: Union[str, None] = 'e9c9aef67bb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_store',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_store_user_id'), 'rate_limit_store', ['user_id'], unique=False)
    op.create_index(op.f('ix_rate_limit_store_ip_address'), 'rate_limit_store', ['ip_address'], unique=False)
    op.create_index(op.f('ix_rate_limit_store_window_start'), 'rate_limit_store', ['window_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_limit_store_window_start'), table_name='rate_limit_store')
    op.drop_index(op.f('ix_rate_limit_store_ip_address'), table_name='rate_limit_store')
    op.drop_index(op.f('ix_rate_limit_store_user_id'), table_name='rate_limit_store')
    op.drop_table('rate_limit_store')
    # ### end Alembic commands ###
